### ISSUE TITLE
Multiple Import Issues (at root of other issues?)

### ISSUE THREAD

**Issue by SwarmShepherd** [bluefireteam/heeve#15]
Multiple messages such as the following: 

Waiting for connection from debug service on Chrome...
lib/building_button.dart:74:8: Error: The method 'BuildingButton.onTapDown' has fewer positional arguments than those of overridden method 'ButtonComponent.onTapDown'.
  bool onTapDown() {
       ^
/C:/tools/flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flame-1.0.0/lib/src/components/input/button_component.dart:56:8: Context: This is the overridden method ('onTapDown').
  bool onTapDown(TapDownInfo info) {
       ^
lib/heeve_game.dart:141:11: Error: Couldn't find constructor 'RotateEffect'.
          RotateEffect(
          ^^^^^^^^^^^^
lib/heeve_game.dart:151:61: Error: The getter 'viewportOnly' isn't defined for the class 'EventPosition'.
 - 'EventPosition' is from 'package:flame/src/gestures/events.dart' ('/C:/tools/flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/flame-1.0.0/lib/src/gestures/events.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'viewportOnly'.
        .where((t) => t.containsPoint(details.eventPosition.viewportOnly))
                                                            ^^^^^^^^^^^^

**Comment by spydon** [comment]
Did you clone `main`? Because in your error you are using Flame 1.0.0, but Heeve is built for rc18 as you can see in the pubspec file.
